os: linux
dist: trusty
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.0

android:
  components:
    - tools
    - platform-tools
  licenses:
    - '.+'
before_install:
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
  - yes | sdkmanager "platforms;android-$ANDROID_API"

script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 --target $JAVA_HOME
  - chmod +x gradlew && ./gradlew clean :app:assembleRelease --stacktrace
